name: python-app-1-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on:  ubuntu-latest
    steps:

      - name: Set short SHA
        shell: bash
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: enequintero/python-app-1:${{ env.SHORT_SHA }}
    outputs:
      commit_id: ${{ env.SHORT_SHA }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app-1/values-dev.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - name: Install Argocd
        shell: bash
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Ensure argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/enequintero/python-app-1.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Create de argocd app
          argocd app get python-app-1 || argocd app create python-app-1 \
            --repo $repo \
            --path charts/python-app-1 \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision main \
            --sync-option CreateNamespace=true
       
      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync python-app-1
          argocd app wait python-app-1 --timeout 180